const nameNormal = "normal";
const nameFire = "fire";
const nameWater = "water";
const nameElectric = "electric";
const nameGrass = "grass";
const nameIce = "ice";
const nameFighting = "fighting";
const namePoison = "poison";
const nameGround = "ground";
const nameFlying = "flying";
const namePsychic = "psychic";
const nameBug = "bug";
const nameRock = "rock";
const nameGhost = "ghost";
const nameDragon = "dragon";
const nameDark = "dark";
const nameSteel = "steel";

const pokemonTypes = [
  // good = super effective when attacking
  // bad = not very effective when attacking
  {
    type: nameNormal,
    good: [],
    bad: [nameRock, nameSteel],
    immune: [nameGhost],
  },
  {
    type: nameFire,
    good: [nameBug, nameSteel, nameGrass, nameIce],
    bad: [nameRock, nameFire, nameWater, nameDragon],
    immune: [],
  },
  {
    type: nameWater,
    good: [nameGround, nameRock, nameFire],
    bad: [nameWater, nameGrass, nameDragon],
    immune: [],
  },
  {
    type: nameElectric,
    good: [nameFlying, nameWater],
    bad: [nameGrass, nameElectric, nameDragon],
    immune: [nameGround],
  },
  {
    type: nameGrass,
    good: [nameGround, nameRock, nameWater],
    bad: [nameFlying, namePoison, nameBug, nameSteel, nameFire, nameGrass, nameDragon],
    immune: [],
  },
  {
    type: nameIce,
    good: [nameFlying, nameGround, nameGrass, nameDragon],
    bad: [nameSteel, nameFire, nameWater, nameIce],
    immune: [],
  },
  {
    type: nameFighting,
    good: [nameNormal, nameRock, nameSteel, nameIce, nameDark],
    bad: [nameFlying, namePoison, nameBug, namePsychic],
    immune: [nameGhost],
  },
  {
    type: namePoison,
    good: [nameGrass],
    bad: [namePoison, nameGround, nameRock, nameGhost],
    immune: [nameSteel],
  },
  {
    type: nameGround,
    good: [namePoison, nameRock, nameSteel, nameFire, nameElectric],
    bad: [nameBug, nameGrass],
    immune: [nameFlying],
  },
  {
    type: nameFlying,
    good: [nameFighting, nameBug, nameGrass],
    bad: [nameRock, nameSteel, nameElectric],
    immune: [],
  },
  {
    type: namePsychic,
    good: [nameFighting, namePoison],
    bad: [nameSteel, namePsychic],
    immune: [nameDark],
  },
  {
    type: nameBug,
    good: [nameGrass, namePsychic, nameDark],
    bad: [nameFighting, nameFlying, namePoison, nameGhost, nameSteel, nameFire],
    immune: [],
  },
  {
    type: nameRock,
    good: [nameFlying, nameBug, nameFire, nameIce],
    bad: [nameFighting, nameGround, nameSteel],
    immune: [],
  },
  {
    type: nameGhost,
    good: [nameGhost, namePsychic],
    bad: [nameDark],
    immune: [nameNormal],
  },
  {
    type: nameDragon,
    good: [nameDragon],
    bad: [nameSteel],
    immune: [],
  },
  {
    type: nameDark,
    good: [nameGhost, namePsychic],
    bad: [nameFighting, nameDark],
    immune: [],
  },
  {
    type: nameSteel,
    good: [nameRock, nameIce],
    bad: [nameSteel, nameFire, nameWater, nameElectric],
    immune: [],
  },
];
const normal = pokemonTypes[0];
const fire = pokemonTypes[1];
const water = pokemonTypes[2];
const electric = pokemonTypes[3];
const grass = pokemonTypes[4];
const ice = pokemonTypes[5];
const fighting = pokemonTypes[6];
const poison = pokemonTypes[7];
const ground = pokemonTypes[8];
const flying = pokemonTypes[9];
const psychic = pokemonTypes[10];
const bug = pokemonTypes[11];
const rock = pokemonTypes[12];
const ghost = pokemonTypes[13];
const dragon = pokemonTypes[14];
const dark = pokemonTypes[15];
const steel = pokemonTypes[16];

const pokemonStats = [
  {
    number: 0,
    name: "",
    type1: "",
    type2: "",
    total: 0,
    hp: 0,
    attack: 0,
    defense: 0,
    sp_attack: 0,
    sp_defense: 0,
    speed: 0,
    generation: 0,
    legendary: "FALSE",
  },
  {
    number: 1,
    name: "Bulbasaur",
    type1: grass,
    type2: poison,
    total: 318,
    hp: 45,
    attack: 49,
    defense: 49,
    sp_attack: 65,
    sp_defense: 65,
    speed: 45,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 2,
    name: "Ivysaur",
    type1: grass,
    type2: poison,
    total: 405,
    hp: 60,
    attack: 62,
    defense: 63,
    sp_attack: 80,
    sp_defense: 80,
    speed: 60,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 3,
    name: "Venusaur",
    type1: grass,
    type2: poison,
    total: 525,
    hp: 80,
    attack: 82,
    defense: 83,
    sp_attack: 100,
    sp_defense: 100,
    speed: 80,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 4,
    name: "Charmander",
    type1: fire,
    type2: "",
    total: 309,
    hp: 39,
    attack: 52,
    defense: 43,
    sp_attack: 60,
    sp_defense: 50,
    speed: 65,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 5,
    name: "Charmeleon",
    type1: fire,
    type2: "",
    total: 405,
    hp: 58,
    attack: 64,
    defense: 58,
    sp_attack: 80,
    sp_defense: 65,
    speed: 80,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 6,
    name: "Charizard",
    type1: fire,
    type2: flying,
    total: 534,
    hp: 78,
    attack: 84,
    defense: 78,
    sp_attack: 109,
    sp_defense: 85,
    speed: 100,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 7,
    name: "Squirtle",
    type1: water,
    type2: "",
    total: 314,
    hp: 44,
    attack: 48,
    defense: 65,
    sp_attack: 50,
    sp_defense: 64,
    speed: 43,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 8,
    name: "Wartortle",
    type1: water,
    type2: "",
    total: 405,
    hp: 59,
    attack: 63,
    defense: 80,
    sp_attack: 65,
    sp_defense: 80,
    speed: 58,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 9,
    name: "Blastoise",
    type1: water,
    type2: "",
    total: 530,
    hp: 79,
    attack: 83,
    defense: 100,
    sp_attack: 85,
    sp_defense: 105,
    speed: 78,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 10,
    name: "Caterpie",
    type1: bug,
    type2: "",
    total: 195,
    hp: 45,
    attack: 30,
    defense: 35,
    sp_attack: 20,
    sp_defense: 20,
    speed: 45,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 11,
    name: "Metapod",
    type1: bug,
    type2: "",
    total: 205,
    hp: 50,
    attack: 20,
    defense: 55,
    sp_attack: 25,
    sp_defense: 25,
    speed: 30,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 12,
    name: "Butterfree",
    type1: bug,
    type2: flying,
    total: 395,
    hp: 60,
    attack: 45,
    defense: 50,
    sp_attack: 90,
    sp_defense: 80,
    speed: 70,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 13,
    name: "Weedle",
    type1: bug,
    type2: poison,
    total: 195,
    hp: 40,
    attack: 35,
    defense: 30,
    sp_attack: 20,
    sp_defense: 20,
    speed: 50,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 14,
    name: "Kakuna",
    type1: bug,
    type2: poison,
    total: 205,
    hp: 45,
    attack: 25,
    defense: 50,
    sp_attack: 25,
    sp_defense: 25,
    speed: 35,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 15,
    name: "Beedrill",
    type1: bug,
    type2: poison,
    total: 395,
    hp: 65,
    attack: 90,
    defense: 40,
    sp_attack: 45,
    sp_defense: 80,
    speed: 75,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 16,
    name: "Pidgey",
    type1: normal,
    type2: flying,
    total: 251,
    hp: 40,
    attack: 45,
    defense: 40,
    sp_attack: 35,
    sp_defense: 35,
    speed: 56,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 17,
    name: "Pidgeotto",
    type1: normal,
    type2: flying,
    total: 349,
    hp: 63,
    attack: 60,
    defense: 55,
    sp_attack: 50,
    sp_defense: 50,
    speed: 71,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 18,
    name: "Pidgeot",
    type1: normal,
    type2: flying,
    total: 479,
    hp: 83,
    attack: 80,
    defense: 75,
    sp_attack: 70,
    sp_defense: 70,
    speed: 101,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 19,
    name: "Rattata",
    type1: normal,
    type2: "",
    total: 253,
    hp: 30,
    attack: 56,
    defense: 35,
    sp_attack: 25,
    sp_defense: 35,
    speed: 72,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 20,
    name: "Raticate",
    type1: normal,
    type2: "",
    total: 413,
    hp: 55,
    attack: 81,
    defense: 60,
    sp_attack: 50,
    sp_defense: 70,
    speed: 97,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 21,
    name: "Spearow",
    type1: normal,
    type2: flying,
    total: 262,
    hp: 40,
    attack: 60,
    defense: 30,
    sp_attack: 31,
    sp_defense: 31,
    speed: 70,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 22,
    name: "Fearow",
    type1: normal,
    type2: flying,
    total: 442,
    hp: 65,
    attack: 90,
    defense: 65,
    sp_attack: 61,
    sp_defense: 61,
    speed: 100,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 23,
    name: "Ekans",
    type1: poison,
    type2: "",
    total: 288,
    hp: 35,
    attack: 60,
    defense: 44,
    sp_attack: 40,
    sp_defense: 54,
    speed: 55,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 24,
    name: "Arbok",
    type1: poison,
    type2: "",
    total: 438,
    hp: 60,
    attack: 85,
    defense: 69,
    sp_attack: 65,
    sp_defense: 79,
    speed: 80,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 25,
    name: "Pikachu",
    type1: electric,
    type2: "",
    total: 320,
    hp: 35,
    attack: 55,
    defense: 40,
    sp_attack: 50,
    sp_defense: 50,
    speed: 90,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 26,
    name: "Raichu",
    type1: electric,
    type2: "",
    total: 485,
    hp: 60,
    attack: 90,
    defense: 55,
    sp_attack: 90,
    sp_defense: 80,
    speed: 110,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 27,
    name: "Sandshrew",
    type1: ground,
    type2: "",
    total: 300,
    hp: 50,
    attack: 75,
    defense: 85,
    sp_attack: 20,
    sp_defense: 30,
    speed: 40,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 28,
    name: "Sandslash",
    type1: ground,
    type2: "",
    total: 450,
    hp: 75,
    attack: 100,
    defense: 110,
    sp_attack: 45,
    sp_defense: 55,
    speed: 65,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 29,
    name: "Nidoran♀",
    type1: poison,
    type2: "",
    total: 275,
    hp: 55,
    attack: 47,
    defense: 52,
    sp_attack: 40,
    sp_defense: 40,
    speed: 41,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 30,
    name: "Nidorina",
    type1: poison,
    type2: "",
    total: 365,
    hp: 70,
    attack: 62,
    defense: 67,
    sp_attack: 55,
    sp_defense: 55,
    speed: 56,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 31,
    name: "Nidoqueen",
    type1: poison,
    type2: ground,
    total: 505,
    hp: 90,
    attack: 92,
    defense: 87,
    sp_attack: 75,
    sp_defense: 85,
    speed: 76,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 32,
    name: "Nidoran♂",
    type1: poison,
    type2: "",
    total: 273,
    hp: 46,
    attack: 57,
    defense: 40,
    sp_attack: 40,
    sp_defense: 40,
    speed: 50,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 33,
    name: "Nidorino",
    type1: poison,
    type2: "",
    total: 365,
    hp: 61,
    attack: 72,
    defense: 57,
    sp_attack: 55,
    sp_defense: 55,
    speed: 65,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 34,
    name: "Nidoking",
    type1: poison,
    type2: ground,
    total: 505,
    hp: 81,
    attack: 102,
    defense: 77,
    sp_attack: 85,
    sp_defense: 75,
    speed: 85,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 35,
    name: "Clefairy",
    type1: normal,
    type2: "",
    total: 323,
    hp: 70,
    attack: 45,
    defense: 48,
    sp_attack: 60,
    sp_defense: 65,
    speed: 35,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 36,
    name: "Clefable",
    type1: normal,
    type2: "",
    total: 483,
    hp: 95,
    attack: 70,
    defense: 73,
    sp_attack: 95,
    sp_defense: 90,
    speed: 60,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 37,
    name: "Vulpix",
    type1: fire,
    type2: "",
    total: 299,
    hp: 38,
    attack: 41,
    defense: 40,
    sp_attack: 50,
    sp_defense: 65,
    speed: 65,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 38,
    name: "Ninetales",
    type1: fire,
    type2: "",
    total: 505,
    hp: 73,
    attack: 76,
    defense: 75,
    sp_attack: 81,
    sp_defense: 100,
    speed: 100,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 39,
    name: "Jigglypuff",
    type1: normal,
    type2: "",
    total: 270,
    hp: 115,
    attack: 45,
    defense: 20,
    sp_attack: 45,
    sp_defense: 25,
    speed: 20,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 40,
    name: "Wigglytuff",
    type1: normal,
    type2: "",
    total: 435,
    hp: 140,
    attack: 70,
    defense: 45,
    sp_attack: 85,
    sp_defense: 50,
    speed: 45,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 41,
    name: "Zubat",
    type1: poison,
    type2: flying,
    total: 245,
    hp: 40,
    attack: 45,
    defense: 35,
    sp_attack: 30,
    sp_defense: 40,
    speed: 55,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 42,
    name: "Golbat",
    type1: poison,
    type2: flying,
    total: 455,
    hp: 75,
    attack: 80,
    defense: 70,
    sp_attack: 65,
    sp_defense: 75,
    speed: 90,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 43,
    name: "Oddish",
    type1: grass,
    type2: poison,
    total: 320,
    hp: 45,
    attack: 50,
    defense: 55,
    sp_attack: 75,
    sp_defense: 65,
    speed: 30,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 44,
    name: "Gloom",
    type1: grass,
    type2: poison,
    total: 395,
    hp: 60,
    attack: 65,
    defense: 70,
    sp_attack: 85,
    sp_defense: 75,
    speed: 40,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 45,
    name: "Vileplume",
    type1: grass,
    type2: poison,
    total: 490,
    hp: 75,
    attack: 80,
    defense: 85,
    sp_attack: 110,
    sp_defense: 90,
    speed: 50,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 46,
    name: "Paras",
    type1: bug,
    type2: grass,
    total: 285,
    hp: 35,
    attack: 70,
    defense: 55,
    sp_attack: 45,
    sp_defense: 55,
    speed: 25,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 47,
    name: "Parasect",
    type1: bug,
    type2: grass,
    total: 405,
    hp: 60,
    attack: 95,
    defense: 80,
    sp_attack: 60,
    sp_defense: 80,
    speed: 30,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 48,
    name: "Venonat",
    type1: bug,
    type2: poison,
    total: 305,
    hp: 60,
    attack: 55,
    defense: 50,
    sp_attack: 40,
    sp_defense: 55,
    speed: 45,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 49,
    name: "Venomoth",
    type1: bug,
    type2: poison,
    total: 450,
    hp: 70,
    attack: 65,
    defense: 60,
    sp_attack: 90,
    sp_defense: 75,
    speed: 90,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 50,
    name: "Diglett",
    type1: ground,
    type2: "",
    total: 265,
    hp: 10,
    attack: 55,
    defense: 25,
    sp_attack: 35,
    sp_defense: 45,
    speed: 95,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 51,
    name: "Dugtrio",
    type1: ground,
    type2: "",
    total: 405,
    hp: 35,
    attack: 80,
    defense: 50,
    sp_attack: 50,
    sp_defense: 70,
    speed: 120,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 52,
    name: "Meowth",
    type1: normal,
    type2: "",
    total: 290,
    hp: 40,
    attack: 45,
    defense: 35,
    sp_attack: 40,
    sp_defense: 40,
    speed: 90,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 53,
    name: "Persian",
    type1: normal,
    type2: "",
    total: 440,
    hp: 65,
    attack: 70,
    defense: 60,
    sp_attack: 65,
    sp_defense: 65,
    speed: 115,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 54,
    name: "Psyduck",
    type1: water,
    type2: "",
    total: 320,
    hp: 50,
    attack: 52,
    defense: 48,
    sp_attack: 65,
    sp_defense: 50,
    speed: 55,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 55,
    name: "Golduck",
    type1: water,
    type2: "",
    total: 500,
    hp: 80,
    attack: 82,
    defense: 78,
    sp_attack: 95,
    sp_defense: 80,
    speed: 85,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 56,
    name: "Mankey",
    type1: fighting,
    type2: "",
    total: 305,
    hp: 40,
    attack: 80,
    defense: 35,
    sp_attack: 35,
    sp_defense: 45,
    speed: 70,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 57,
    name: "Primeape",
    type1: fighting,
    type2: "",
    total: 455,
    hp: 65,
    attack: 105,
    defense: 60,
    sp_attack: 60,
    sp_defense: 70,
    speed: 95,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 58,
    name: "Growlithe",
    type1: fire,
    type2: "",
    total: 350,
    hp: 55,
    attack: 70,
    defense: 45,
    sp_attack: 70,
    sp_defense: 50,
    speed: 60,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 59,
    name: "Arcanine",
    type1: fire,
    type2: "",
    total: 555,
    hp: 90,
    attack: 110,
    defense: 80,
    sp_attack: 100,
    sp_defense: 80,
    speed: 95,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 60,
    name: "Poliwag",
    type1: water,
    type2: "",
    total: 300,
    hp: 40,
    attack: 50,
    defense: 40,
    sp_attack: 40,
    sp_defense: 40,
    speed: 90,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 61,
    name: "Poliwhirl",
    type1: water,
    type2: "",
    total: 385,
    hp: 65,
    attack: 65,
    defense: 65,
    sp_attack: 50,
    sp_defense: 50,
    speed: 90,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 62,
    name: "Poliwrath",
    type1: water,
    type2: fighting,
    total: 510,
    hp: 90,
    attack: 95,
    defense: 95,
    sp_attack: 70,
    sp_defense: 90,
    speed: 70,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 63,
    name: "Abra",
    type1: psychic,
    type2: "",
    total: 310,
    hp: 25,
    attack: 20,
    defense: 15,
    sp_attack: 105,
    sp_defense: 55,
    speed: 90,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 64,
    name: "Kadabra",
    type1: psychic,
    type2: "",
    total: 400,
    hp: 40,
    attack: 35,
    defense: 30,
    sp_attack: 120,
    sp_defense: 70,
    speed: 105,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 65,
    name: "Alakazam",
    type1: psychic,
    type2: "",
    total: 500,
    hp: 55,
    attack: 50,
    defense: 45,
    sp_attack: 135,
    sp_defense: 95,
    speed: 120,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 66,
    name: "Machop",
    type1: fighting,
    type2: "",
    total: 305,
    hp: 70,
    attack: 80,
    defense: 50,
    sp_attack: 35,
    sp_defense: 35,
    speed: 35,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 67,
    name: "Machoke",
    type1: fighting,
    type2: "",
    total: 405,
    hp: 80,
    attack: 100,
    defense: 70,
    sp_attack: 50,
    sp_defense: 60,
    speed: 45,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 68,
    name: "Machamp",
    type1: fighting,
    type2: "",
    total: 505,
    hp: 90,
    attack: 130,
    defense: 80,
    sp_attack: 65,
    sp_defense: 85,
    speed: 55,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 69,
    name: "Bellsprout",
    type1: grass,
    type2: poison,
    total: 300,
    hp: 50,
    attack: 75,
    defense: 35,
    sp_attack: 70,
    sp_defense: 30,
    speed: 40,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 70,
    name: "Weepinbell",
    type1: grass,
    type2: poison,
    total: 390,
    hp: 65,
    attack: 90,
    defense: 50,
    sp_attack: 85,
    sp_defense: 45,
    speed: 55,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 71,
    name: "Victreebel",
    type1: grass,
    type2: poison,
    total: 490,
    hp: 80,
    attack: 105,
    defense: 65,
    sp_attack: 100,
    sp_defense: 70,
    speed: 70,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 72,
    name: "Tentacool",
    type1: water,
    type2: poison,
    total: 335,
    hp: 40,
    attack: 40,
    defense: 35,
    sp_attack: 50,
    sp_defense: 100,
    speed: 70,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 73,
    name: "Tentacruel",
    type1: water,
    type2: poison,
    total: 515,
    hp: 80,
    attack: 70,
    defense: 65,
    sp_attack: 80,
    sp_defense: 120,
    speed: 100,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 74,
    name: "Geodude",
    type1: rock,
    type2: ground,
    total: 300,
    hp: 40,
    attack: 80,
    defense: 100,
    sp_attack: 30,
    sp_defense: 30,
    speed: 20,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 75,
    name: "Graveler",
    type1: rock,
    type2: ground,
    total: 390,
    hp: 55,
    attack: 95,
    defense: 115,
    sp_attack: 45,
    sp_defense: 45,
    speed: 35,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 76,
    name: "Golem",
    type1: rock,
    type2: ground,
    total: 495,
    hp: 80,
    attack: 120,
    defense: 130,
    sp_attack: 55,
    sp_defense: 65,
    speed: 45,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 77,
    name: "Ponyta",
    type1: fire,
    type2: "",
    total: 410,
    hp: 50,
    attack: 85,
    defense: 55,
    sp_attack: 65,
    sp_defense: 65,
    speed: 90,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 78,
    name: "Rapidash",
    type1: fire,
    type2: "",
    total: 500,
    hp: 65,
    attack: 100,
    defense: 70,
    sp_attack: 80,
    sp_defense: 80,
    speed: 105,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 79,
    name: "Slowpoke",
    type1: water,
    type2: psychic,
    total: 315,
    hp: 90,
    attack: 65,
    defense: 65,
    sp_attack: 40,
    sp_defense: 40,
    speed: 15,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 80,
    name: "Slowbro",
    type1: water,
    type2: psychic,
    total: 490,
    hp: 95,
    attack: 75,
    defense: 110,
    sp_attack: 100,
    sp_defense: 80,
    speed: 30,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 81,
    name: "Magnemite",
    type1: electric,
    type2: steel,
    total: 325,
    hp: 25,
    attack: 35,
    defense: 70,
    sp_attack: 95,
    sp_defense: 55,
    speed: 45,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 82,
    name: "Magneton",
    type1: electric,
    type2: steel,
    total: 465,
    hp: 50,
    attack: 60,
    defense: 95,
    sp_attack: 120,
    sp_defense: 70,
    speed: 70,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 83,
    name: "Farfetch'd",
    type1: normal,
    type2: flying,
    total: 352,
    hp: 52,
    attack: 90,
    defense: 55,
    sp_attack: 58,
    sp_defense: 62,
    speed: 60,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 84,
    name: "Doduo",
    type1: normal,
    type2: flying,
    total: 310,
    hp: 35,
    attack: 85,
    defense: 45,
    sp_attack: 35,
    sp_defense: 35,
    speed: 75,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 85,
    name: "Dodrio",
    type1: normal,
    type2: flying,
    total: 460,
    hp: 60,
    attack: 110,
    defense: 70,
    sp_attack: 60,
    sp_defense: 60,
    speed: 100,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 86,
    name: "Seel",
    type1: water,
    type2: "",
    total: 325,
    hp: 65,
    attack: 45,
    defense: 55,
    sp_attack: 45,
    sp_defense: 70,
    speed: 45,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 87,
    name: "Dewgong",
    type1: water,
    type2: ice,
    total: 475,
    hp: 90,
    attack: 70,
    defense: 80,
    sp_attack: 70,
    sp_defense: 95,
    speed: 70,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 88,
    name: "Grimer",
    type1: poison,
    type2: "",
    total: 325,
    hp: 80,
    attack: 80,
    defense: 50,
    sp_attack: 40,
    sp_defense: 50,
    speed: 25,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 89,
    name: "Muk",
    type1: poison,
    type2: "",
    total: 500,
    hp: 105,
    attack: 105,
    defense: 75,
    sp_attack: 65,
    sp_defense: 100,
    speed: 50,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 90,
    name: "Shellder",
    type1: water,
    type2: "",
    total: 305,
    hp: 30,
    attack: 65,
    defense: 100,
    sp_attack: 45,
    sp_defense: 25,
    speed: 40,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 91,
    name: "Cloyster",
    type1: water,
    type2: ice,
    total: 525,
    hp: 50,
    attack: 95,
    defense: 180,
    sp_attack: 85,
    sp_defense: 45,
    speed: 70,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 92,
    name: "Gastly",
    type1: ghost,
    type2: poison,
    total: 310,
    hp: 30,
    attack: 35,
    defense: 30,
    sp_attack: 100,
    sp_defense: 35,
    speed: 80,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 93,
    name: "Haunter",
    type1: ghost,
    type2: poison,
    total: 405,
    hp: 45,
    attack: 50,
    defense: 45,
    sp_attack: 115,
    sp_defense: 55,
    speed: 95,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 94,
    name: "Gengar",
    type1: ghost,
    type2: poison,
    total: 500,
    hp: 60,
    attack: 65,
    defense: 60,
    sp_attack: 130,
    sp_defense: 75,
    speed: 110,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 95,
    name: "Onix",
    type1: rock,
    type2: ground,
    total: 385,
    hp: 35,
    attack: 45,
    defense: 160,
    sp_attack: 30,
    sp_defense: 45,
    speed: 70,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 96,
    name: "Drowzee",
    type1: psychic,
    type2: "",
    total: 328,
    hp: 60,
    attack: 48,
    defense: 45,
    sp_attack: 43,
    sp_defense: 90,
    speed: 42,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 97,
    name: "Hypno",
    type1: psychic,
    type2: "",
    total: 483,
    hp: 85,
    attack: 73,
    defense: 70,
    sp_attack: 73,
    sp_defense: 115,
    speed: 67,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 98,
    name: "Krabby",
    type1: water,
    type2: "",
    total: 325,
    hp: 30,
    attack: 105,
    defense: 90,
    sp_attack: 25,
    sp_defense: 25,
    speed: 50,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 99,
    name: "Kingler",
    type1: water,
    type2: "",
    total: 475,
    hp: 55,
    attack: 130,
    defense: 115,
    sp_attack: 50,
    sp_defense: 50,
    speed: 75,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 100,
    name: "Voltorb",
    type1: electric,
    type2: "",
    total: 330,
    hp: 40,
    attack: 30,
    defense: 50,
    sp_attack: 55,
    sp_defense: 55,
    speed: 100,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 101,
    name: "Electrode",
    type1: electric,
    type2: "",
    total: 480,
    hp: 60,
    attack: 50,
    defense: 70,
    sp_attack: 80,
    sp_defense: 80,
    speed: 140,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 102,
    name: "Exeggcute",
    type1: grass,
    type2: psychic,
    total: 325,
    hp: 60,
    attack: 40,
    defense: 80,
    sp_attack: 60,
    sp_defense: 45,
    speed: 40,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 103,
    name: "Exeggutor",
    type1: grass,
    type2: psychic,
    total: 520,
    hp: 95,
    attack: 95,
    defense: 85,
    sp_attack: 125,
    sp_defense: 65,
    speed: 55,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 104,
    name: "Cubone",
    type1: ground,
    type2: "",
    total: 320,
    hp: 50,
    attack: 50,
    defense: 95,
    sp_attack: 40,
    sp_defense: 50,
    speed: 35,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 105,
    name: "Marowak",
    type1: ground,
    type2: "",
    total: 425,
    hp: 60,
    attack: 80,
    defense: 110,
    sp_attack: 50,
    sp_defense: 80,
    speed: 45,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 106,
    name: "Hitmonlee",
    type1: fighting,
    type2: "",
    total: 455,
    hp: 50,
    attack: 120,
    defense: 53,
    sp_attack: 35,
    sp_defense: 110,
    speed: 87,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 107,
    name: "Hitmonchan",
    type1: fighting,
    type2: "",
    total: 455,
    hp: 50,
    attack: 105,
    defense: 79,
    sp_attack: 35,
    sp_defense: 110,
    speed: 76,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 108,
    name: "Lickitung",
    type1: normal,
    type2: "",
    total: 385,
    hp: 90,
    attack: 55,
    defense: 75,
    sp_attack: 60,
    sp_defense: 75,
    speed: 30,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 109,
    name: "Koffing",
    type1: poison,
    type2: "",
    total: 340,
    hp: 40,
    attack: 65,
    defense: 95,
    sp_attack: 60,
    sp_defense: 45,
    speed: 35,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 110,
    name: "Weezing",
    type1: poison,
    type2: "",
    total: 490,
    hp: 65,
    attack: 90,
    defense: 120,
    sp_attack: 85,
    sp_defense: 70,
    speed: 60,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 111,
    name: "Rhyhorn",
    type1: ground,
    type2: rock,
    total: 345,
    hp: 80,
    attack: 85,
    defense: 95,
    sp_attack: 30,
    sp_defense: 30,
    speed: 25,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 112,
    name: "Rhydon",
    type1: ground,
    type2: rock,
    total: 485,
    hp: 105,
    attack: 130,
    defense: 120,
    sp_attack: 45,
    sp_defense: 45,
    speed: 40,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 113,
    name: "Chansey",
    type1: normal,
    type2: "",
    total: 450,
    hp: 250,
    attack: 5,
    defense: 5,
    sp_attack: 35,
    sp_defense: 105,
    speed: 50,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 114,
    name: "Tangela",
    type1: grass,
    type2: "",
    total: 435,
    hp: 65,
    attack: 55,
    defense: 115,
    sp_attack: 100,
    sp_defense: 40,
    speed: 60,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 115,
    name: "Kangaskhan",
    type1: normal,
    type2: "",
    total: 490,
    hp: 105,
    attack: 95,
    defense: 80,
    sp_attack: 40,
    sp_defense: 80,
    speed: 90,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 116,
    name: "Horsea",
    type1: water,
    type2: "",
    total: 295,
    hp: 30,
    attack: 40,
    defense: 70,
    sp_attack: 70,
    sp_defense: 25,
    speed: 60,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 117,
    name: "Seadra",
    type1: water,
    type2: "",
    total: 440,
    hp: 55,
    attack: 65,
    defense: 95,
    sp_attack: 95,
    sp_defense: 45,
    speed: 85,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 118,
    name: "Goldeen",
    type1: water,
    type2: "",
    total: 320,
    hp: 45,
    attack: 67,
    defense: 60,
    sp_attack: 35,
    sp_defense: 50,
    speed: 63,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 119,
    name: "Seaking",
    type1: water,
    type2: "",
    total: 450,
    hp: 80,
    attack: 92,
    defense: 65,
    sp_attack: 65,
    sp_defense: 80,
    speed: 68,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 120,
    name: "Staryu",
    type1: water,
    type2: "",
    total: 340,
    hp: 30,
    attack: 45,
    defense: 55,
    sp_attack: 70,
    sp_defense: 55,
    speed: 85,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 121,
    name: "Starmie",
    type1: water,
    type2: psychic,
    total: 520,
    hp: 60,
    attack: 75,
    defense: 85,
    sp_attack: 100,
    sp_defense: 85,
    speed: 115,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 122,
    name: "Mr. Mime",
    type1: psychic,
    type2: "",
    total: 460,
    hp: 40,
    attack: 45,
    defense: 65,
    sp_attack: 100,
    sp_defense: 120,
    speed: 90,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 123,
    name: "Scyther",
    type1: bug,
    type2: flying,
    total: 500,
    hp: 70,
    attack: 110,
    defense: 80,
    sp_attack: 55,
    sp_defense: 80,
    speed: 105,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 124,
    name: "Jynx",
    type1: ice,
    type2: psychic,
    total: 455,
    hp: 65,
    attack: 50,
    defense: 35,
    sp_attack: 115,
    sp_defense: 95,
    speed: 95,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 125,
    name: "Electabuzz",
    type1: electric,
    type2: "",
    total: 490,
    hp: 65,
    attack: 83,
    defense: 57,
    sp_attack: 95,
    sp_defense: 85,
    speed: 105,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 126,
    name: "Magmar",
    type1: fire,
    type2: "",
    total: 495,
    hp: 65,
    attack: 95,
    defense: 57,
    sp_attack: 100,
    sp_defense: 85,
    speed: 93,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 127,
    name: "Pinsir",
    type1: bug,
    type2: "",
    total: 500,
    hp: 65,
    attack: 125,
    defense: 100,
    sp_attack: 55,
    sp_defense: 70,
    speed: 85,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 128,
    name: "Tauros",
    type1: normal,
    type2: "",
    total: 490,
    hp: 75,
    attack: 100,
    defense: 95,
    sp_attack: 40,
    sp_defense: 70,
    speed: 110,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 129,
    name: "Magikarp",
    type1: water,
    type2: "",
    total: 200,
    hp: 20,
    attack: 10,
    defense: 55,
    sp_attack: 15,
    sp_defense: 20,
    speed: 80,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 130,
    name: "Gyarados",
    type1: water,
    type2: flying,
    total: 540,
    hp: 95,
    attack: 125,
    defense: 79,
    sp_attack: 60,
    sp_defense: 100,
    speed: 81,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 131,
    name: "Lapras",
    type1: water,
    type2: ice,
    total: 535,
    hp: 130,
    attack: 85,
    defense: 80,
    sp_attack: 85,
    sp_defense: 95,
    speed: 60,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 132,
    name: "Ditto",
    type1: normal,
    type2: "",
    total: 288,
    hp: 48,
    attack: 48,
    defense: 48,
    sp_attack: 48,
    sp_defense: 48,
    speed: 48,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 133,
    name: "Eevee",
    type1: normal,
    type2: "",
    total: 325,
    hp: 55,
    attack: 55,
    defense: 50,
    sp_attack: 45,
    sp_defense: 65,
    speed: 55,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 134,
    name: "Vaporeon",
    type1: water,
    type2: "",
    total: 525,
    hp: 130,
    attack: 65,
    defense: 60,
    sp_attack: 110,
    sp_defense: 95,
    speed: 65,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 135,
    name: "Jolteon",
    type1: electric,
    type2: "",
    total: 525,
    hp: 65,
    attack: 65,
    defense: 60,
    sp_attack: 110,
    sp_defense: 95,
    speed: 130,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 136,
    name: "Flareon",
    type1: fire,
    type2: "",
    total: 525,
    hp: 65,
    attack: 130,
    defense: 60,
    sp_attack: 95,
    sp_defense: 110,
    speed: 65,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 137,
    name: "Porygon",
    type1: normal,
    type2: "",
    total: 395,
    hp: 65,
    attack: 60,
    defense: 70,
    sp_attack: 85,
    sp_defense: 75,
    speed: 40,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 138,
    name: "Omanyte",
    type1: rock,
    type2: water,
    total: 355,
    hp: 35,
    attack: 40,
    defense: 100,
    sp_attack: 90,
    sp_defense: 55,
    speed: 35,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 139,
    name: "Omastar",
    type1: rock,
    type2: water,
    total: 495,
    hp: 70,
    attack: 60,
    defense: 125,
    sp_attack: 115,
    sp_defense: 70,
    speed: 55,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 140,
    name: "Kabuto",
    type1: rock,
    type2: water,
    total: 355,
    hp: 30,
    attack: 80,
    defense: 90,
    sp_attack: 55,
    sp_defense: 45,
    speed: 55,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 141,
    name: "Kabutops",
    type1: rock,
    type2: water,
    total: 495,
    hp: 60,
    attack: 115,
    defense: 105,
    sp_attack: 65,
    sp_defense: 70,
    speed: 80,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 142,
    name: "Aerodactyl",
    type1: rock,
    type2: flying,
    total: 515,
    hp: 80,
    attack: 105,
    defense: 65,
    sp_attack: 60,
    sp_defense: 75,
    speed: 130,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 143,
    name: "Snorlax",
    type1: normal,
    type2: "",
    total: 540,
    hp: 160,
    attack: 110,
    defense: 65,
    sp_attack: 65,
    sp_defense: 110,
    speed: 30,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 144,
    name: "Articuno",
    type1: ice,
    type2: flying,
    total: 580,
    hp: 90,
    attack: 85,
    defense: 100,
    sp_attack: 95,
    sp_defense: 125,
    speed: 85,
    generation: 1,
    legendary: "TRUE",
  },
  {
    number: 145,
    name: "Zapdos",
    type1: electric,
    type2: flying,
    total: 580,
    hp: 90,
    attack: 90,
    defense: 85,
    sp_attack: 125,
    sp_defense: 90,
    speed: 100,
    generation: 1,
    legendary: "TRUE",
  },
  {
    number: 146,
    name: "Moltres",
    type1: fire,
    type2: flying,
    total: 580,
    hp: 90,
    attack: 100,
    defense: 90,
    sp_attack: 125,
    sp_defense: 85,
    speed: 90,
    generation: 1,
    legendary: "TRUE",
  },
  {
    number: 147,
    name: "Dratini",
    type1: dragon,
    type2: "",
    total: 300,
    hp: 41,
    attack: 64,
    defense: 45,
    sp_attack: 50,
    sp_defense: 50,
    speed: 50,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 148,
    name: "Dragonair",
    type1: dragon,
    type2: "",
    total: 420,
    hp: 61,
    attack: 84,
    defense: 65,
    sp_attack: 70,
    sp_defense: 70,
    speed: 70,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 149,
    name: "Dragonite",
    type1: dragon,
    type2: flying,
    total: 600,
    hp: 91,
    attack: 134,
    defense: 95,
    sp_attack: 100,
    sp_defense: 100,
    speed: 80,
    generation: 1,
    legendary: "FALSE",
  },
  {
    number: 150,
    name: "Mewtwo",
    type1: psychic,
    type2: "",
    total: 680,
    hp: 106,
    attack: 110,
    defense: 90,
    sp_attack: 154,
    sp_defense: 90,
    speed: 130,
    generation: 1,
    legendary: "TRUE",
  },
  {
    number: 151,
    name: "Mew",
    type1: psychic,
    type2: "",
    total: 600,
    hp: 100,
    attack: 100,
    defense: 100,
    sp_attack: 100,
    sp_defense: 100,
    speed: 100,
    generation: 1,
    legendary: "TRUE",
  },
];

const pokemonMoves = [
  {
    name: "Struggle",
    id: 0,
    type: "none",
    category: "none",
    pp: 0,
    attack: 20,
    accuracy: 0,
    description: "",
    target: "enemy",
    effect: "atkSelf",
    status: "",
    chance: "",
    rate: 1
  },
  {
    name: "Leech Life",
    id: 1,
    type: "bug",
    category: "physical",
    pp: 15,
    attack: 20,
    accuracy: 100,
    description: "An HP-draining attack. It adds half the HP it drained from the target to the attacker's HP.",
    target: "enemy",
    effect: "atkHeal",
    status: "",
    chance: "",
    rate: 2
  },
  {
    name: "Pin Missile",
    id: 2,
    type: "bug",
    category: "physical",
    pp: 20,
    attack: 14,
    accuracy: 85,
    description: "An attack that fires many needle-like projectiles from the body. Strikes several times.",
    target: "enemy",
    effect: "atkMulti",
    status: "",
    chance: "",
    rate: 5
  },
  {
    name: "String Shot",
    id: 3,
    type: "bug",
    category: "status",
    pp: 40,
    attack: 0,
    accuracy: 95,
    description: "Strings are sprayed out and wrapped around the target to reduce its SPEED.",
    target: "enemy",
    effect: "debuff",
    status: "SPD",
    chance: 1,
    rate: 1
  },
  {
    name: "Bite",
    id: 4,
    type: "dark",
    category: "physical",
    pp: 25,
    attack: 60,
    accuracy: 100,
    description: "A bite made using sharp fangs. This may cause the opponent to flinch, and it might not attack.",
    target: "enemy",
    effect: "atkStatus",
    status: "flinch",
    chance: 4,
    rate: ""
  },
  {
    name: "Crunch",
    id: 5,
    type: "dark",
    category: "physical",
    pp: 15,
    attack: 80,
    accuracy: 100,
    description: "Has a one-in-five chance of reducing the target's SPECIAL DEFENSE.",
    target: "enemy",
    effect: "atkDebuff",
    status: "SPDEF",
    chance: 5,
    rate: 1
  },
  {
    name: "Faint Attack",
    id: 6,
    type: "dark",
    category: "physical",
    pp: 20,
    attack: 60,
    accuracy: 0,
    description: "The move catches the opponent off guard, so it never misses.",
    target: "enemy",
    effect: "atkNoMiss",
    status: "",
    chance: "",
    rate: ""
  },
  {
    name: "Dragon Rush",
    id: 7,
    type: "dragon",
    category: "physical",
    pp: 10,
    attack: 100,
    accuracy: 75,
    description: "The user tackles the foe while exhibiting overwhelming menace. It may also make the target flinch.",
    target: "enemy",
    effect: "atkStatus",
    status: "flinch",
    chance: 4,
    rate: ""
  },
  {
    name: "Dragon Pulse",
    id: 8,
    type: "dragon",
    category: "special",
    pp: 10,
    attack: 90,
    accuracy: 100,
    description: "The foe is attacked with a shock wave generated by the user's gaping mouth.",
    target: "enemy",
    effect: "atk",
    status: "",
    chance: "",
    rate: ""
  },
  {
    name: "Thunder",
    id: 9,
    type: "electric",
    category: "special",
    pp: 10,
    attack: 120,
    accuracy: 70,
    description: "Has a one-in-ten chance of paralyzing the target.",
    target: "enemy",
    effect: "atkStatus",
    status: "paralyze",
    chance: 10,
    rate: ""
  },
  {
    name: "Thunder Punch",
    id: 10,
    type: "electric",
    category: "physical",
    pp: 15,
    attack: 75,
    accuracy: 100,
    description: "Has a one-in-ten chance of paralyzing the target.",
    target: "enemy",
    effect: "atkStatus",
    status: "paralyze",
    chance: 10,
    rate: ""
  },
  {
    name: "Thunder Shock",
    id: 11,
    type: "electric",
    category: "special",
    pp: 30,
    attack: 40,
    accuracy: 100,
    description: "Has a one-in-ten chance of paralyzing the target.",
    target: "enemy",
    effect: "atkStatus",
    status: "paralyze",
    chance: 10,
    rate: ""
  },
  {
    name: "Thunder Wave",
    id: 12,
    type: "electric",
    category: "status",
    pp: 20,
    attack: 0,
    accuracy: 100,
    description: "A special move that causes paralysis. When paralyzed, the victim has a one-in-four chance of immobility.",
    target: "enemy",
    effect: "atkStatus",
    status: "paralyze",
    chance: 4,
    rate: ""
  },
  {
    name: "Thunderbolt",
    id: 13,
    type: "electric",
    category: "special",
    pp: 15,
    attack: 95,
    accuracy: 100,
    description: "Has a one-in-ten chance of paralyzing the target.",
    target: "enemy",
    effect: "atkStatus",
    status: "paralyze",
    chance: 10,
    rate: ""
  },
  {
    name: "Double Kick",
    id: 14,
    type: "fighting",
    category: "physical",
    pp: 30,
    attack: 30,
    accuracy: 100,
    description: "As the name implies, it is actually two quick kicks in succession.",
    target: "enemy",
    effect: "atkMulti",
    status: "",
    chance: "",
    rate: 2
  },
  {
    name: "Low Kick",
    id: 15,
    type: "fighting",
    category: "physical",
    pp: 20,
    attack: 50,
    accuracy: 90,
    description: "Has a one-in-three chance of making the target flinch if it connects.",
    target: "enemy",
    effect: "atkStatus",
    status: "flinch",
    chance: 3,
    rate: ""
  },
  {
    name: "Rolling Kick",
    id: 16,
    type: "fighting",
    category: "physical",
    pp: 15,
    attack: 60,
    accuracy: 85,
    description: "Has a one-in-three chance of making the target flinch if it connects.",
    target: "enemy",
    effect: "atkStatus",
    status: "flinch",
    chance: 3,
    rate: ""
  },
  {
    name: "Seismic Toss",
    id: 17,
    type: "fighting",
    category: "physical",
    pp: 20,
    attack: 0,
    accuracy: 100,
    description: "Throws the target with enough force to flip the world upside down.",
    target: "enemy",
    effect: "atk",
    status: "",
    chance: "",
    rate: ""
  },
  {
    name: "Submission",
    id: 18,
    type: "fighting",
    category: "physical",
    pp: 25,
    attack: 80,
    accuracy: 80,
    description: "One quarter of the damage it inflicts comes back to hurt the attacker.",
    target: "enemy",
    effect: "atkSelf",
    status: "",
    chance: "",
    rate: ""
  },
  {
    name: "Ember",
    id: 19,
    type: "fire",
    category: "special",
    pp: 25,
    attack: 40,
    accuracy: 100,
    description: "Has a one-in-ten chance of leaving the target with a damaging burn.",
    target: "enemy",
    effect: "atkStatus",
    status: "burn",
    chance: 10,
    rate: ""
  },
  {
    name: "Fire Blast",
    id: 20,
    type: "fire",
    category: "special",
    pp: 5,
    attack: 120,
    accuracy: 85,
    description: "Has a one-in-three chance of inflicting a burn on the target.",
    target: "enemy",
    effect: "atkStatus",
    status: "burn",
    chance: 3,
    rate: ""
  },
  {
    name: "Fire Punch",
    id: 21,
    type: "fire",
    category: "physical",
    pp: 15,
    attack: 75,
    accuracy: 100,
    description: "Has a one-in-ten chance of inflicting a burn on the target.",
    target: "enemy",
    effect: "atkStatus",
    status: "burn",
    chance: 10,
    rate: ""
  },
  {
    name: "Flamethrower",
    id: 22,
    type: "fire",
    category: "special",
    pp: 15,
    attack: 95,
    accuracy: 100,
    description: "Has a one-in-ten chance of leaving the target with a damaging burn.",
    target: "enemy",
    effect: "atkStatus",
    status: "burn",
    chance: 10,
    rate: ""
  },
  {
    name: "Drill Peck",
    id: 23,
    type: "flying",
    category: "physical",
    pp: 20,
    attack: 80,
    accuracy: 100,
    description: "It is strong and highly likely to hit the target.",
    target: "enemy",
    effect: "atk",
    status: "",
    chance: "",
    rate: ""
  },
  {
    name: "Fly",
    id: 24,
    type: "flying",
    category: "physical",
    pp: 15,
    attack: 70,
    accuracy: 95,
    description: "The Pokémon flies high, then strikes in the next turn.",
    target: "enemy",
    effect: "atkDelay",
    status: "",
    chance: "",
    rate: ""
  },
  {
    name: "Peck",
    id: 25,
    type: "flying",
    category: "physical",
    pp: 35,
    attack: 35,
    accuracy: 100,
    description: "It is favored by Pokémon that have beaks and/or horns.",
    target: "enemy",
    effect: "atk",
    status: "",
    chance: "",
    rate: ""
  },
  {
    name: "Sky Attack",
    id: 26,
    type: "flying",
    category: "physical",
    pp: 5,
    attack: 140,
    accuracy: 90,
    description: "Energy is stored in the first turn, then fired the next turn.",
    target: "enemy",
    effect: "atkDelay",
    status: "",
    chance: "",
    rate: ""
  },
  {
    name: "Wing Attack",
    id: 27,
    type: "flying",
    category: "physical",
    pp: 35,
    attack: 35,
    accuracy: 100,
    description: "The attacking Pokémon spreads its wings and charges at the target.",
    target: "enemy",
    effect: "atk",
    status: "",
    chance: "",
    rate: ""
  },
  {
    name: "Confuse Ray",
    id: 28,
    type: "ghost",
    category: "status",
    pp: 10,
    attack: 0,
    accuracy: 100,
    description: "A sinister flash of light makes the target confused.",
    target: "enemy",
    effect: "status",
    status: "confuse",
    chance: 1,
    rate: 2
  },
  {
    name: "Lick",
    id: 29,
    type: "ghost",
    category: "physical",
    pp: 30,
    attack: 20,
    accuracy: 100,
    description: "Has a one-in-three chance of leaving the target with paralysis.",
    target: "enemy",
    effect: "atkStatus",
    status: "paralyze",
    chance: 3,
    rate: ""
  },
  {
    name: "Shadow Punch",
    id: 30,
    type: "ghost",
    category: "physical",
    pp: 20,
    attack: 60,
    accuracy: 0,
    description: "The user throws a punch at the foe from the shadows. The punch lands without fail.",
    target: "enemy",
    effect: "atkNoMiss",
    status: "",
    chance: "",
    rate: ""
  },
  {
    name: "Absorb",
    id: 31,
    type: "grass",
    category: "special",
    pp: 20,
    attack: 20,
    accuracy: 100,
    description: "It adds half the HP it drained from the target to the attacker's HP.",
    target: "enemy",
    effect: "atkHeal",
    status: "",
    chance: "",
    rate: ""
  },
  {
    name: "Mega Drain",
    id: 32,
    type: "grass",
    category: "special",
    pp: 10,
    attack: 40,
    accuracy: 100,
    description: "It adds half the HP it drained from the target to the attacker's HP.",
    target: "enemy",
    effect: "atkHeal",
    status: "",
    chance: "",
    rate: ""
  },
  {
    name: "Razor Leaf",
    id: 33,
    type: "grass",
    category: "physical",
    pp: 25,
    attack: 55,
    accuracy: 95,
    description: "An attack that sends sharp-edged leaves at the target. Likely to get a critical hit.",
    target: "enemy",
    effect: "atkCrit",
    status: "",
    chance: "",
    rate: ""
  },
  {
    name: "Sleep Powder",
    id: 34,
    type: "grass",
    category: "status",
    pp: 15,
    attack: 0,
    accuracy: 75,
    description: "Induces sleep. A Pokémon may wake up in less than 2 turns.",
    target: "enemy",
    effect: "status",
    status: "sleep",
    chance: 1,
    rate: 2
  },
  {
    name: "Solar Beam",
    id: 35,
    type: "grass",
    category: "special",
    pp: 10,
    attack: 120,
    accuracy: 100,
    description: "Energy is absorbed in the first turn, then fired the next turn.",
    target: "enemy",
    effect: "atkDelay",
    status: "",
    chance: "",
    rate: ""
  },
  {
    name: "Spore",
    id: 36,
    type: "grass",
    category: "status",
    pp: 15,
    attack: 0,
    accuracy: 100,
    description: "Special spores are scattered from mushrooms. If the opponent inhales the spores, it will fall asleep.",
    target: "enemy",
    effect: "status",
    status: "sleep",
    chance: 1,
    rate: 2
  },
  {
    name: "Stun Spore",
    id: 37,
    type: "grass",
    category: "status",
    pp: 30,
    attack: 0,
    accuracy: 75,
    description: "A special move that causes paralysis. When paralyzed, the victim has a one-in-four chance of immobility.",
    target: "enemy",
    effect: "status",
    status: "paralyze",
    chance: 4,
    rate: ""
  },
  {
    name: "Vine Whip",
    id: 38,
    type: "grass",
    category: "physical",
    pp: 10,
    attack: 35,
    accuracy: 100,
    description: "The Pokémon uses its cruel whips to strike the opponent.",
    target: "enemy",
    effect: "atk",
    status: "",
    chance: "",
    rate: ""
  },
  {
    name: "Bone Club",
    id: 39,
    type: "ground",
    category: "physical",
    pp: 20,
    attack: 65,
    accuracy: 85,
    description: "A physical attack using a bone as a club. If it connects, it may cause the target to flinch.",
    target: "enemy",
    effect: "atkStatus",
    status: "flinch",
    chance: 4,
    rate: ""
  },
  {
    name: "Bonemerang",
    id: 40,
    type: "ground",
    category: "physical",
    pp: 10,
    attack: 50,
    accuracy: 90,
    description: "A boomerang made of bone is thrown to inflict damage.",
    target: "enemy",
    effect: "atk",
    status: "",
    chance: "",
    rate: ""
  },
  {
    name: "Dig",
    id: 41,
    type: "ground",
    category: "physical",
    pp: 10,
    attack: 100,
    accuracy: 100,
    description: "The attacker digs underground in the first turn, then pops up in the next turn to attack.",
    target: "enemy",
    effect: "atkDelay",
    status: "",
    chance: "",
    rate: ""
  },
  {
    name: "Earthquake",
    id: 42,
    type: "ground",
    category: "physical",
    pp: 10,
    attack: 100,
    accuracy: 100,
    description: "An attack that inflicts damage by shaking the ground.",
    target: "enemy",
    effect: "atk",
    status: "",
    chance: "",
    rate: ""
  },
  {
    name: "Sand-Attack",
    id: 43,
    type: "ground",
    category: "status",
    pp: 15,
    attack: 0,
    accuracy: 100,
    description: "An attack in which sand is used to blind the target and reduce its attack accuracy.",
    target: "enemy",
    effect: "debuff",
    status: "ACC",
    chance: 1,
    rate: 1
  },
  {
    name: "Aurora Beam",
    id: 44,
    type: "ice",
    category: "special",
    pp: 20,
    attack: 65,
    accuracy: 100,
    description: "Has a one-in-three chance of reducing the target's ATTACK power.",
    target: "enemy",
    effect: "atkDebuff",
    status: "ATK",
    chance: 3,
    rate: 1
  },
  {
    name: "Blizzard",
    id: 45,
    type: "ice",
    category: "special",
    pp: 5,
    attack: 120,
    accuracy: 90,
    description: "Has a one-in-ten chance of freezing the target solid.",
    target: "enemy",
    effect: "atkStatus",
    status: "freeze",
    chance: 10,
    rate: ""
  },
  {
    name: "Ice Beam",
    id: 46,
    type: "ice",
    category: "special",
    pp: 10,
    attack: 95,
    accuracy: 100,
    description: "Has a one-in-ten chance of freezing the target solid.",
    target: "enemy",
    effect: "atkStatus",
    status: "freeze",
    chance: 10,
    rate: ""
  },
  {
    name: "Ice Punch",
    id: 47,
    type: "ice",
    category: "physical",
    pp: 15,
    attack: 75,
    accuracy: 100,
    description: "Has a one-in-ten chance of freezing the target.",
    target: "enemy",
    effect: "atkStatus",
    status: "freeze",
    chance: 10,
    rate: ""
  },
  {
    name: "Mist",
    id: 48,
    type: "ice",
    category: "status",
    pp: 30,
    attack: 0,
    accuracy: 100,
    description: "Provides full protection against any enemy status attack, such as those that lower DEFENSE.",
    target: "enemy",
    effect: "debuffBlock",
    status: "",
    chance: "",
    rate: ""
  },
  {
    name: "Body Slam",
    id: 49,
    type: "normal",
    category: "physical",
    pp: 15,
    attack: 85,
    accuracy: 100,
    description: "Has a one-in-three chance of paralyzing the target if it connects.",
    target: "enemy",
    effect: "atkStatus",
    status: "paralyze",
    chance: 3,
    rate: ""
  },
  {
    name: "Comet Punch",
    id: 50,
    type: "normal",
    category: "physical",
    pp: 15,
    attack: 18,
    accuracy: 85,
    description: "Although each slap is weak, this attack hits the target two to five times in succession.",
    target: "enemy",
    effect: "atkMulti",
    status: "",
    chance: "",
    rate: 5
  },
  {
    name: "Defense Curl",
    id: 51,
    type: "normal",
    category: "status",
    pp: 40,
    attack: 0,
    accuracy: 100,
    description: "Raises the user's DEFENSE. Can normally be used up to six times in a row.",
    target: "player",
    effect: "buff",
    status: "DEF",
    chance: 1,
    rate: 1
  },
  {
    name: "Double Team",
    id: 52,
    type: "normal",
    category: "status",
    pp: 15,
    attack: 0,
    accuracy: 100,
    description: "Creates illusionary copies of the user. The copies disorient the enemy, reducing its accuracy.",
    target: "enemy",
    effect: "debuff",
    status: "ACC",
    chance: 1,
    rate: 1
  },
  {
    name: "Double-Edge",
    id: 53,
    type: "normal",
    category: "physical",
    pp: 15,
    attack: 100,
    accuracy: 100,
    description: "A charging tackle attack. One quarter of the damage it inflicts comes back to hurt the attacker.",
    target: "enemy",
    effect: "atkSelf",
    status: "",
    chance: "",
    rate: ""
  },
  {
    name: "Glare",
    id: 54,
    type: "normal",
    category: "status",
    pp: 30,
    attack: 0,
    accuracy: 75,
    description: "The target is transfixed with terrifying sharp eyes. The target is frightened into paralysis.",
    target: "enemy",
    effect: "status",
    status: "paralyze",
    chance: 1,
    rate: ""
  },
  {
    name: "Growl",
    id: 55,
    type: "normal",
    category: "status",
    pp: 40,
    attack: 0,
    accuracy: 100,
    description: "A technique that lowers the target's ATTACK power. Can normally be used up to six times.",
    target: "enemy",
    effect: "debuff",
    status: "ATK",
    chance: 1,
    rate: 1
  },
  {
    name: "Growth",
    id: 56,
    type: "normal",
    category: "status",
    pp: 40,
    attack: 0,
    accuracy: 100,
    description: "Raises SPECIAL ATTACK to make special attacks stronger.",
    target: "player",
    effect: "buff",
    status: "SPATK",
    chance: 1,
    rate: 1
  },
  {
    name: "Harden",
    id: 57,
    type: "normal",
    category: "status",
    pp: 30,
    attack: 0,
    accuracy: 100,
    description: "Raises the user's DEFENSE. Useful when battling physically strong Pokémon.",
    target: "player",
    effect: "buff",
    status: "DEF",
    chance: 1,
    rate: 1
  },
  {
    name: "Headbutt",
    id: 58,
    type: "normal",
    category: "physical",
    pp: 15,
    attack: 70,
    accuracy: 100,
    description: "Has a one-in-three chance of making the target flinch if it connects.",
    target: "enemy",
    effect: "atkStatus",
    status: "flinch",
    chance: 3,
    rate: ""
  },
  {
    name: "Horn Attack",
    id: 59,
    type: "normal",
    category: "physical",
    pp: 25,
    attack: 65,
    accuracy: 100,
    description: "A sharp horn is driven hard into the target to inflict damage.",
    target: "enemy",
    effect: "atk",
    status: "",
    chance: "",
    rate: ""
  },
  {
    name: "Hyper Fang",
    id: 60,
    type: "normal",
    category: "physical",
    pp: 15,
    attack: 80,
    accuracy: 90,
    description: "Has a one-in-ten chance of making the target flinch.",
    target: "enemy",
    effect: "atkStatus",
    status: "flinch",
    chance: 10,
    rate: ""
  },
  {
    name: "Lovely Kiss",
    id: 61,
    type: "normal",
    category: "status",
    pp: 10,
    attack: 0,
    accuracy: 75,
    description: "A special move that puts the target to sleep with a big kiss. (Actually, the victim passes out.)",
    target: "enemy",
    effect: "status",
    status: "sleep",
    chance: 1,
    rate: ""
  },
  {
    name: "Mega Punch",
    id: 62,
    type: "normal",
    category: "physical",
    pp: 20,
    attack: 80,
    accuracy: 85,
    description: "It is highly accurate and relatively powerful.",
    target: "enemy",
    effect: "atk",
    status: "",
    chance: "",
    rate: ""
  },
  {
    name: "Quick Attack",
    id: 63,
    type: "normal",
    category: "physical",
    pp: 30,
    attack: 40,
    accuracy: 100,
    description: "An attack that always strikes first. If both Pokémon use this, the one with higher SPEED attacks first.",
    target: "enemy",
    effect: "atkPriority",
    status: "",
    chance: "",
    rate: ""
  },
  {
    name: "Screech",
    id: 64,
    type: "normal",
    category: "status",
    pp: 40,
    attack: 0,
    accuracy: 85,
    description: "A move that makes a horrible noise. It sharply reduces the target's DEFENSE.",
    target: "enemy",
    effect: "debuff",
    status: "DEF",
    chance: 1,
    rate: 2
  },
  {
    name: "Sharpen",
    id: 65,
    type: "normal",
    category: "status",
    pp: 30,
    attack: 0,
    accuracy: 100,
    description: "Raises the user's ATTACK power. The edges of the Pokémon are made harder for more impact.",
    target: "player",
    effect: "buff",
    status: "ATK",
    chance: 1,
    rate: 1
  },
  {
    name: "Acid",
    id: 66,
    type: "poison",
    category: "special",
    pp: 30,
    attack: 40,
    accuracy: 100,
    description: "Has a one-in-three chance of lowering the target's DEFENSE.",
    target: "enemy",
    effect: "atkDebuff",
    status: "DEF",
    chance: 3,
    rate: 1
  },
  {
    name: "Acid Armor",
    id: 67,
    type: "poison",
    category: "status",
    pp: 40,
    attack: 0,
    accuracy: 100,
    description: "Melts the user's body for protection. A move that sharply raises DEFENSE.",
    target: "player",
    effect: "buff",
    status: "DEF",
    chance: 1,
    rate: 2
  },
  {
    name: "Poison Fang",
    id: 68,
    type: "poison",
    category: "physical",
    pp: 15,
    attack: 50,
    accuracy: 100,
    description: "The user bites the foe with toxic fangs. It may also leave the foe badly poisoned.",
    target: "enemy",
    effect: "atkStatus",
    status: "poison",
    chance: 4,
    rate: ""
  },
  {
    name: "Poison Powder",
    id: 69,
    type: "poison",
    category: "status",
    pp: 35,
    attack: 0,
    accuracy: 75,
    description: "A technique that poisons the target. If poisoned, the victim loses HP steadily.",
    target: "enemy",
    effect: "status",
    status: "poison",
    chance: 1,
    rate: ""
  },
  {
    name: "Sludge",
    id: 70,
    type: "poison",
    category: "special",
    pp: 20,
    attack: 65,
    accuracy: 100,
    description: "Has a fifty-fifty chance of poisoning the target.",
    target: "enemy",
    effect: "atkStatus",
    status: "poison",
    chance: 2,
    rate: ""
  },
  {
    name: "Agility",
    id: 71,
    type: "psychic",
    category: "status",
    pp: 30,
    attack: 0,
    accuracy: 100,
    description: "A special technique that greatly boosts the user's SPEED. Can normally be used up to three times.",
    target: "player",
    effect: "buff",
    status: "SPD",
    chance: 1,
    rate: 2
  },
  {
    name: "Amnesia",
    id: 72,
    type: "psychic",
    category: "status",
    pp: 20,
    attack: 0,
    accuracy: 100,
    description: "Sharply raises the user's SPECIAL DEFENSE stat.",
    target: "player",
    effect: "buff",
    status: "SPDEF",
    chance: 1,
    rate: 2
  },
  {
    name: "Barrier",
    id: 73,
    type: "psychic",
    category: "status",
    pp: 30,
    attack: 0,
    accuracy: 100,
    description: "Instantly forms a barrier between the user and the opponent. DEFENSE is sharply increased.",
    target: "player",
    effect: "buff",
    status: "DEF",
    chance: 1,
    rate: 2
  },
  {
    name: "Confusion",
    id: 74,
    type: "psychic",
    category: "special",
    pp: 25,
    attack: 50,
    accuracy: 100,
    description: "Has a one-in-ten chance of leaving the target confused.",
    target: "enemy",
    effect: "atkStatus",
    status: "confuse",
    chance: 10,
    rate: ""
  },
  {
    name: "Hypnosis",
    id: 75,
    type: "psychic",
    category: "status",
    pp: 20,
    attack: 0,
    accuracy: 60,
    description: "The target is hypnotized into a deep sleep.",
    target: "enemy",
    effect: "status",
    status: "sleep",
    chance: 1,
    rate: 3
  },
  {
    name: "Kinesis",
    id: 76,
    type: "psychic",
    category: "status",
    pp: 15,
    attack: 0,
    accuracy: 80,
    description: "A special move of bending spoons to confound the enemy. Makes the user harder to hit.",
    target: "enemy",
    effect: "debuff",
    status: "ACC",
    chance: 1,
    rate: 1
  },
  {
    name: "Meditate",
    id: 77,
    type: "psychic",
    category: "status",
    pp: 40,
    attack: 0,
    accuracy: 100,
    description: "A special technique that boosts the user's ATTACK power. Can normally be used up to six times.",
    target: "enemy",
    effect: "buff",
    status: "ATK",
    chance: 1,
    rate: 1
  },
  {
    name: "Psybeam",
    id: 78,
    type: "psychic",
    category: "special",
    pp: 20,
    attack: 65,
    accuracy: 100,
    description: "Has a one-in-ten chance of making the target confused.",
    target: "enemy",
    effect: "atkStatus",
    status: "confuse",
    chance: 10,
    rate: ""
  },
  {
    name: "Psychic",
    id: 79,
    type: "psychic",
    category: "special",
    pp: 10,
    attack: 90,
    accuracy: 100,
    description: "Has a one-in-three chance of lowering the target's SPECIAL ATTACK.",
    target: "enemy",
    effect: "atkDebuff",
    status: "SPATK",
    chance: 3,
    rate: ""
  },
  {
    name: "Rest",
    id: 80,
    type: "psychic",
    category: "status",
    pp: 10,
    attack: 0,
    accuracy: 100,
    description: "The user takes a nap to fully restore its HP and recover from any status abnormalities.",
    target: "player",
    effect: "heal",
    status: "sleep",
    chance: 1,
    rate: 2
  },
  {
    name: "Rock Slide",
    id: 81,
    type: "rock",
    category: "physical",
    pp: 10,
    attack: 75,
    accuracy: 90,
    description: "An attack that hits the target with an avalanche of rocks and boulders.",
    target: "enemy",
    effect: "atk",
    status: "",
    chance: "",
    rate: ""
  },
  {
    name: "Rock Throw",
    id: 82,
    type: "rock",
    category: "physical",
    pp: 15,
    attack: 50,
    accuracy: 65,
    description: "As the name implies, a huge boulder is dropped on the target.",
    target: "enemy",
    effect: "atk",
    status: "",
    chance: "",
    rate: ""
  },
  {
    name: "Iron Head",
    id: 83,
    type: "steel",
    category: "physical",
    pp: 15,
    attack: 80,
    accuracy: 100,
    description: "The foe slams the target with its steel-hard head. It may also make the target flinch.",
    target: "enemy",
    effect: "atkStatus",
    status: "flinch",
    chance: 4,
    rate: ""
  },
  {
    name: "Iron Tail",
    id: 84,
    type: "steel",
    category: "physical",
    pp: 15,
    attack: 100,
    accuracy: 75,
    description: "The foe is slammed with a steel-hard tail. It may also lower the target's Defense stat.",
    target: "enemy",
    effect: "atkDebuff",
    status: "DEF",
    chance: 5,
    rate: 1
  },
  {
    name: "Mirror Shot",
    id: 85,
    type: "steel",
    category: "special",
    pp: 10,
    attack: 65,
    accuracy: 85,
    description: "The user looses a flash of energy from its polished body. It may also lower the target's accuracy.",
    target: "enemy",
    effect: "atkDebuff",
    status: "ACC",
    chance: 5,
    rate: 1
  },
  {
    name: "Bubble Beam",
    id: 86,
    type: "water",
    category: "special",
    pp: 20,
    attack: 65,
    accuracy: 100,
    description: "Has a one-in-three chance of reducing the target's SPEED.",
    target: "enemy",
    effect: "atkDebuff",
    status: "SPD",
    chance: 3,
    rate: 1
  },
  {
    name: "Hydro Pump",
    id: 87,
    type: "water",
    category: "special",
    pp: 5,
    attack: 120,
    accuracy: 80,
    description: "However, while it is powerful, it may miss the target.",
    target: "enemy",
    effect: "atk",
    status: "",
    chance: "",
    rate: ""
  },
  {
    name: "Surf",
    id: 88,
    type: "water",
    category: "special",
    pp: 15,
    attack: 95,
    accuracy: 100,
    description: "The power of this technique is strong and highly accurate.",
    target: "enemy",
    effect: "atk",
    status: "",
    chance: "",
    rate: ""
  },
  {
    name: "Waterfall",
    id: 89,
    type: "water",
    category: "physical",
    pp: 15,
    attack: 80,
    accuracy: 100,
    description: "The target is hit with a blow packing the power of fish traveling up waterfalls.",
    target: "enemy",
    effect: "atk"
  }
];
// stage multipliers
// stage = 0 base = 2; multiplier = 2; totalMultiplier = 0
// if (stage == 0) {} 
// else if (stage > 0){totalMultiplier = (multiplier + stage) / base} the stage is positive
// else if (stage < 0){totalMultiplier = base / (multiplier - stage)} the stage is negative 